file1 = open("30days30hoursoperations.txt","w+")
file1.write("I have completed 10days successfully \n")
file1.close()
file1 = open("30days30hoursoperations.txt","r+")
print(file1.read())
file1.write("Aparna\n")
file1.close()
file1 = open("30days30hoursoperations.txt","r+")
print(file1.read())